### ISSUE TITLE
Faraday::ConnectionFailed: Connection reset by peer

### ISSUE THREAD

**Issue by FSCgithub** [Restream/redmine_elasticsearch#45]
Hi,
I am expierencing an "Faraday::ConnectionFailed: Connection reset by peer" error when initially indexing (-> reindexing) all documents after importing issues (~7,000 !) from another ticket system.

```
 # bundle exec rake redmine_elasticsearch:reindex_all RAILS_ENV=production --trace
```
```
  Loading Rails environment for Resque
  ** Invoke redmine_elasticsearch:reindex_all (first_time)
  ** Invoke redmine_elasticsearch:logged (first_time)
  ** Invoke environment (first_time)
  ** Execute environment
  ** Execute redmine_elasticsearch:logged
  ** Execute redmine_elasticsearch:reindex_all
  Recreating index and updating mapping...
  Available search types: [issues, news, documents, changesets, wiki_pages, messages, projects]
  
  Counting projects...
  12 will be imported.
  Project tree:  100% |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| Time: 00:00:00
  Done reindex project tree. Errors: 0
  
  Counting estimated records for issues...
  6992 will be imported.
  rake aborted!  100% |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| ETA:  00:00:00
  Faraday::ConnectionFailed: Connection reset by peer
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:211:in `write'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:211:in `write0'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:185:in `block in write'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:202:in `writing'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:184:in `write'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http/generic_request.rb:187:in `send_request_with_body'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http/generic_request.rb:120:in `exec'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1412:in `block in transport_request'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1384:in `request'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:853:in `start'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1375:in `request'
  /usr/local/rvm/gems/ruby-2.2.1/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
  /usr/local/rvm/gems/ruby-2.2.1/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
  /usr/local/rvm/gems/ruby-2.2.1/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
  /usr/local/rvm/gems/ruby-2.2.1/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:33:in `call'
  /usr/local/rvm/gems/ruby-2.2.1/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
  /usr/local/rvm/gems/ruby-2.2.1/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
  /usr/local/rvm/gems/ruby-2.2.1/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/http/faraday.rb:23:in `block in perform_request'
  /usr/local/rvm/gems/ruby-2.2.1/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:262:in `call'
  /usr/local/rvm/gems/ruby-2.2.1/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:262:in `perform_request'
  /usr/local/rvm/gems/ruby-2.2.1/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  /usr/local/rvm/gems/ruby-2.2.1/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/client.rb:131:in `perform_request'
  /usr/local/rvm/gems/ruby-2.2.1/gems/elasticsearch-api-5.0.4/lib/elasticsearch/api/actions/bulk.rb:95:in `bulk'
  /opt/redmine-3.3.1/plugins/redmine_elasticsearch/app/elastic/application_search.rb:72:in `block in import'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:124:in `find_in_batches'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:9:in `find_in_batches'
  /opt/redmine-3.3.1/plugins/redmine_elasticsearch/app/elastic/application_search.rb:71:in `import'
  /opt/redmine-3.3.1/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/indexer_service.rb:48:in `reindex'
  /opt/redmine-3.3.1/plugins/redmine_elasticsearch/lib/tasks/index.rake:86:in `reindex_document_type'
  /opt/redmine-3.3.1/plugins/redmine_elasticsearch/lib/tasks/index.rake:28:in `block (3 levels) in <top (required)>'
  /opt/redmine-3.3.1/plugins/redmine_elasticsearch/lib/tasks/index.rake:27:in `each'
  /opt/redmine-3.3.1/plugins/redmine_elasticsearch/lib/tasks/index.rake:27:in `block (2 levels) in <top (required)>'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/task.rb:250:in `call'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.2.1/bin/rake:23:in `load'
  /usr/local/rvm/gems/ruby-2.2.1/bin/rake:23:in `<main>'
  /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
  /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
  Errno::ECONNRESET: Connection reset by peer
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:211:in `write'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:211:in `write0'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:185:in `block in write'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:202:in `writing'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:184:in `write'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http/generic_request.rb:187:in `send_request_with_body'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http/generic_request.rb:120:in `exec'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1412:in `block in transport_request'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1384:in `request'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:853:in `start'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1375:in `request'
  /usr/local/rvm/gems/ruby-2.2.1/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
  /usr/local/rvm/gems/ruby-2.2.1/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
  /usr/local/rvm/gems/ruby-2.2.1/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
  /usr/local/rvm/gems/ruby-2.2.1/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:33:in `call'
  /usr/local/rvm/gems/ruby-2.2.1/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
  /usr/local/rvm/gems/ruby-2.2.1/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
  /usr/local/rvm/gems/ruby-2.2.1/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/http/faraday.rb:23:in `block in perform_request'
  /usr/local/rvm/gems/ruby-2.2.1/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:262:in `call'
  /usr/local/rvm/gems/ruby-2.2.1/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:262:in `perform_request'
  /usr/local/rvm/gems/ruby-2.2.1/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  /usr/local/rvm/gems/ruby-2.2.1/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/client.rb:131:in `perform_request'
  /usr/local/rvm/gems/ruby-2.2.1/gems/elasticsearch-api-5.0.4/lib/elasticsearch/api/actions/bulk.rb:95:in `bulk'
  /opt/redmine-3.3.1/plugins/redmine_elasticsearch/app/elastic/application_search.rb:72:in `block in import'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:124:in `find_in_batches'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:9:in `find_in_batches'
  /opt/redmine-3.3.1/plugins/redmine_elasticsearch/app/elastic/application_search.rb:71:in `import'
  /opt/redmine-3.3.1/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/indexer_service.rb:48:in `reindex'
  /opt/redmine-3.3.1/plugins/redmine_elasticsearch/lib/tasks/index.rake:86:in `reindex_document_type'
  /opt/redmine-3.3.1/plugins/redmine_elasticsearch/lib/tasks/index.rake:28:in `block (3 levels) in <top (required)>'
  /opt/redmine-3.3.1/plugins/redmine_elasticsearch/lib/tasks/index.rake:27:in `each'
  /opt/redmine-3.3.1/plugins/redmine_elasticsearch/lib/tasks/index.rake:27:in `block (2 levels) in <top (required)>'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/task.rb:250:in `call'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
  /usr/local/rvm/gems/ruby-2.2.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.2.1/bin/rake:23:in `load'
  /usr/local/rvm/gems/ruby-2.2.1/bin/rake:23:in `<main>'
  /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
  /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
  Tasks: TOP => redmine_elasticsearch:reindex_all
```

My ```plugins/redmine_elasticsearch/config/configuration.yml``` is
```
  default:
    elasticsearch:
      log: true
      request_timeout: 300
      host: '127.0.0.1'
      port: 9200
```

I am using Elasticsearch 5.4.3 on a CentOS 7.2.1511 system:
```
{
  "name" : "RM-DEV",
  "cluster_name" : "rm-cl",
  "cluster_uuid" : "-tQmjvDTRBql0ibEQp-3tA",
  "version" : {
    "number" : "5.4.3",
    "build_hash" : "eed30a8",
    "build_date" : "2017-06-22T00:34:03.743Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.1"
  },
  "tagline" : "You Know, for Search"
}
```
My ```/etc/elasticsearch/elasticsearch.yml``` is
```
cluster.name: rm-cl
node.name: "RM-DEV"
network.host: localhost
http.port: 9200
```

I am running Elasticsearch as systemd service with ```/etc/sysconfig/elasticsearch```:
```
ES_HOME=/usr/share/elasticsearch
CONF_DIR=/etc/elasticsearch
DATA_DIR=/var/lib/elasticsearch
LOG_DIR=/var/log/elasticsearch
WORK_DIR=/tmp/elasticsearch
PID_DIR=/var/run/elasticsearch
ES_JAVA_OPTS="-Xms2g -Xmx2g"
ES_USER=elasticsearch
ES_GROUP=elasticsearch
MAX_OPEN_FILES=65535
#MAX_LOCKED_MEMORY=unlimited
MAX_MAP_COUNT=262144
```

I had a look at https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport
The section about "Setting Timeouts" says that request_timeout parameter is simply set by
```
request_timeout: <timeout_in_sec>
```
but it seems that my setting of ``` request_timeout: 300``` does not work?!

Is there anybody who has an idea?

-Thanks in advance for any hints...
Frank

**Comment by FSCgithub** [comment]
Here is the `/var/log/elasticsearch/rm-cl.log`: 
```
...
[2017-07-03T10:22:29,708][INFO ][o.e.c.m.MetaDataDeleteIndexService] [RM-DEV] [redmineapp_production/YM1uVfvEQpiXSiTMlAgh1A] deleting index
[2017-07-03T10:22:29,862][INFO ][o.e.c.m.MetaDataCreateIndexService] [RM-DEV] [redmineapp_production] creating index, cause [api], templates [], shards [1]/[0], mappings [_default_]
[2017-07-03T10:22:29,900][INFO ][o.e.c.r.a.AllocationService] [RM-DEV] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[redmineapp_production][0]] ...]).
[2017-07-03T10:22:29,920][INFO ][o.e.c.m.MetaDataMappingService] [RM-DEV] [redmineapp_production/1wM83UmuRB2uHOtRF7u60g] create_mapping [issue]
[2017-07-03T10:22:29,941][INFO ][o.e.c.m.MetaDataMappingService] [RM-DEV] [redmineapp_production/1wM83UmuRB2uHOtRF7u60g] create_mapping [news]
[2017-07-03T10:22:29,968][INFO ][o.e.c.m.MetaDataMappingService] [RM-DEV] [redmineapp_production/1wM83UmuRB2uHOtRF7u60g] create_mapping [document]
[2017-07-03T10:22:29,995][INFO ][o.e.c.m.MetaDataMappingService] [RM-DEV] [redmineapp_production/1wM83UmuRB2uHOtRF7u60g] create_mapping [changeset]
[2017-07-03T10:22:30,023][INFO ][o.e.c.m.MetaDataMappingService] [RM-DEV] [redmineapp_production/1wM83UmuRB2uHOtRF7u60g] create_mapping [wiki_page]
[2017-07-03T10:22:30,048][INFO ][o.e.c.m.MetaDataMappingService] [RM-DEV] [redmineapp_production/1wM83UmuRB2uHOtRF7u60g] create_mapping [message]
[2017-07-03T10:22:30,073][INFO ][o.e.c.m.MetaDataMappingService] [RM-DEV] [redmineapp_production/1wM83UmuRB2uHOtRF7u60g] create_mapping [project]
[2017-07-03T10:22:30,266][INFO ][o.e.c.m.MetaDataMappingService] [RM-DEV] [redmineapp_production/1wM83UmuRB2uHOtRF7u60g] create_mapping [parent_project]
[2017-07-03T10:22:58,738][INFO ][o.e.c.m.MetaDataMappingService] [RM-DEV] [redmineapp_production/1wM83UmuRB2uHOtRF7u60g] update_mapping [issue]
[2017-07-03T10:22:58,764][INFO ][o.e.c.m.MetaDataMappingService] [RM-DEV] [redmineapp_production/1wM83UmuRB2uHOtRF7u60g] update_mapping [issue]
[2017-07-03T10:22:58,796][INFO ][o.e.c.m.MetaDataMappingService] [RM-DEV] [redmineapp_production/1wM83UmuRB2uHOtRF7u60g] update_mapping [issue]
[2017-07-03T10:22:58,828][INFO ][o.e.c.m.MetaDataMappingService] [RM-DEV] [redmineapp_production/1wM83UmuRB2uHOtRF7u60g] update_mapping [issue]
[2017-07-03T10:23:03,441][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38136] overhead, spent [559ms] collecting in the last [1s]
[2017-07-03T10:25:12,307][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38263] overhead, spent [2s] collecting in the last [2.7s]
[2017-07-03T10:25:18,570][INFO ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38269] overhead, spent [496ms] collecting in the last [1.2s]
[2017-07-03T10:25:29,020][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38279] overhead, spent [1s] collecting in the last [1.4s]
[2017-07-03T10:25:30,023][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38280] overhead, spent [520ms] collecting in the last [1s]
[2017-07-03T10:25:31,515][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][young][38281][231] duration [1.2s], collections [1]/[1.4s], total [1.2s]/[9.9s], memory [1.1gb]->[1gb]/[1.9gb], all_pools {[young] [73.7mb]->[2.8mb]/[266.2mb]}{[survivor] [33.2mb]->[33.2mb]/[33.2mb]}{[old] [1gb]->[1gb]/[1.6gb]}
[2017-07-03T10:25:31,516][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38281] overhead, spent [1.2s] collecting in the last [1.4s]
[2017-07-03T10:25:32,521][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38282] overhead, spent [547ms] collecting in the last [1s]
[2017-07-03T10:25:33,558][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38283] overhead, spent [622ms] collecting in the last [1s]
[2017-07-03T10:25:34,564][INFO ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38284] overhead, spent [514ms] collecting in the last [1s]
[2017-07-03T10:25:35,719][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38285] overhead, spent [592ms] collecting in the last [1.1s]
[2017-07-03T10:25:37,378][INFO ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38286] overhead, spent [761ms] collecting in the last [1.6s]
[2017-07-03T10:25:42,693][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][young][38289][240] duration [2s], collections [1]/[3s], total [2s]/[15.3s], memory [1.4gb]->[1.3gb]/[1.9gb], all_pools {[young] [168.3mb]->[12.2mb]/[266.2mb]}{[survivor] [32.3mb]->[33.2mb]/[33.2mb]}{[old] [1.2gb]->[1.3gb]/[1.6gb]}
[2017-07-03T10:25:42,723][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38289] overhead, spent [2s] collecting in the last [3s]
[2017-07-03T10:25:45,302][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][young][38291][241] duration [1s], collections [1]/[1.3s], total [1s]/[16.3s], memory [1.5gb]->[1.4gb]/[1.9gb], all_pools {[young] [158.8mb]->[3.4mb]/[266.2mb]}{[survivor] [33.2mb]->[33.2mb]/[33.2mb]}{[old] [1.3gb]->[1.3gb]/[1.6gb]}
[2017-07-03T10:25:45,303][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38291] overhead, spent [1s] collecting in the last [1.3s]
[2017-07-03T10:26:27,507][INFO ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][young][38332][253] duration [1.6s], collections [2]/[2.1s], total [1.6s]/[18.1s], memory [1007mb]->[1.1gb]/[1.9gb], all_pools {[young] [47.7mb]->[82.4mb]/[266.2mb]}{[survivor] [448.4kb]->[1.4mb]/[33.2mb]}{[old] [958.8mb]->[1gb]/[1.6gb]}
[2017-07-03T10:26:27,509][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38332] overhead, spent [1.6s] collecting in the last [2.1s]
[2017-07-03T10:26:29,855][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][young][38333][254] duration [1.8s], collections [1]/[2.3s], total [1.8s]/[20s], memory [1.1gb]->[1.2gb]/[1.9gb], all_pools {[young] [82.4mb]->[3.4mb]/[266.2mb]}{[survivor] [1.4mb]->[2.1mb]/[33.2mb]}{[old] [1gb]->[1.2gb]/[1.6gb]}
[2017-07-03T10:26:29,855][WARN ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38333] overhead, spent [1.8s] collecting in the last [2.3s]
[2017-07-03T10:26:55,349][INFO ][o.e.m.j.JvmGcMonitorService] [RM-DEV] [gc][38358] overhead, spent [482ms] collecting in the last [1s]
...
```

**Comment by FSCgithub** [comment]
Update: Issue #25 inspired us to reduce the batch size to `BATCH_SIZE=10` which **works** for our (re)indexing of the ~7,000 imported issues:
```
bundle exec rake redmine_elasticsearch:reindex_all RAILS_ENV=production BATCH_SIZE=10
```
So, this issue can be closed!
