### ISSUE TITLE
Faraday::ConnectionFailed: Connection reset by peer

### ISSUE THREAD

**Issue by dallakyan** [Restream/redmine_elasticsearch#47]
This is similar to #45 but I can't get it working even with BATCH_SIZE=1

> [redmine-3.0.4]# bundle exec rake redmine_elasticsearch:reindex_all RAILS_ENV=production BATCH_SIZE=1                                          Loading Rails environment for Resque
> Recreating index and updating mapping...
> Available search types: [issues, news, documents, changesets, wiki_pages, messages, projects]
> 
> Counting projects...
> 140 will be imported.
> Project tree:  100% |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| Time: 00:00:05
> Done reindex project tree. Errors: 0
> 
> Counting estimated records for issues...
> 5488 will be imported.
> rake aborted!   22% ||||||||||||||||||||||||||                                                                                         | ETA:  00:05:03
> Faraday::ConnectionFailed: Connection reset by peer
> /usr/local/rvm/gems/ruby-2.0.0-p353/gems/faraday-0.15.0/lib/faraday/adapter/net_http.rb:82:in `perform_request'
> /usr/local/rvm/gems/ruby-2.0.0-p353/gems/faraday-0.15.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
> /usr/local/rvm/gems/ruby-2.0.0-p353/gems/faraday-0.15.0/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
> /usr/local/rvm/gems/ruby-2.0.0-p353/gems/faraday-0.15.0/lib/faraday/adapter/net_http.rb:33:in `call'
> /usr/local/rvm/gems/ruby-2.0.0-p353/gems/faraday-0.15.0/lib/faraday/rack_builder.rb:143:in `build_response'
> /usr/local/rvm/gems/ruby-2.0.0-p353/gems/faraday-0.15.0/lib/faraday/connection.rb:387:in `run_request'
> /usr/local/rvm/gems/ruby-2.0.0-p353/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/http/faraday.rb:23:in `block in perform_request'
> /usr/local/rvm/gems/ruby-2.0.0-p353/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/base.rb:262:in `call'
> /usr/local/rvm/gems/ruby-2.0.0-p353/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/base.rb:262:in `perform_request'
> /usr/local/rvm/gems/ruby-2.0.0-p353/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
> /usr/local/rvm/gems/ruby-2.0.0-p353/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/client.rb:131:in `perform_request'
> /usr/local/rvm/gems/ruby-2.0.0-p353/gems/elasticsearch-api-5.0.5/lib/elasticsearch/api/actions/bulk.rb:95:in `bulk'
> /srv/www/redmine-3.0.4/plugins/redmine_elasticsearch/app/elastic/application_search.rb:72:in `block in import'
> /usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.2.3/lib/active_record/relation/batches.rb:124:in `find_in_batches'
> /usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.2.3/lib/active_record/querying.rb:9:in `find_in_batches'
> /srv/www/redmine-3.0.4/plugins/redmine_elasticsearch/app/elastic/application_search.rb:71:in `import'
> /srv/www/redmine-3.0.4/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/indexer_service.rb:48:in `reindex'
> /srv/www/redmine-3.0.4/plugins/redmine_elasticsearch/lib/tasks/index.rake:86:in `reindex_document_type'
> /srv/www/redmine-3.0.4/plugins/redmine_elasticsearch/lib/tasks/index.rake:28:in `block (3 levels) in <top (required)>'
> /srv/www/redmine-3.0.4/plugins/redmine_elasticsearch/lib/tasks/index.rake:27:in `each'
> /srv/www/redmine-3.0.4/plugins/redmine_elasticsearch/lib/tasks/index.rake:27:in `block (2 levels) in <top (required)>'
> /usr/local/rvm/gems/ruby-2.0.0-p353/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
> /usr/local/rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
> /usr/local/rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
> Tasks: TOP => redmine_elasticsearch:reindex_all
> (See full trace by running task with --trace)
> 

Is there anything else I can try? Thanks.

**Comment by mtolava** [comment]
Do you check this? https://github.com/Restream/redmine_elasticsearch/issues/45
